#!/usr/bin/env bash
set -euo pipefail

# Render deployment-local Asterisk/PJSIP endpoint configuration for 7001-7007.
# SIP passwords are read from the environment and never accepted as CLI args.
# The generated file is runtime-only and must remain outside Git.

OUTPUT=${1:-runtime/ims/pjsip.conf}
OUTPUT_DIR=$(dirname "$OUTPUT")
umask 077
mkdir -p "$OUTPUT_DIR"
TMP=$(mktemp "$OUTPUT_DIR/.pjsip.conf.XXXXXX")
trap 'rm -f "$TMP"' EXIT

: "${MM7_ASTERISK_CERT_FILE:=/etc/asterisk/keys/mm7-asterisk.crt}"
: "${MM7_ASTERISK_KEY_FILE:=/etc/asterisk/keys/mm7-asterisk.key}"
: "${MM7_ASTERISK_CA_FILE:=/etc/asterisk/keys/mm7-ca.crt}"

cat >"$TMP" <<EOF
; Generated by project-72-render-asterisk-pjsip.sh
; Runtime-only configuration. Do not commit this file.

[global]
type=global
user_agent=MINI-MOBILE-7-Asterisk

[transport-tls]
type=transport
protocol=tls
bind=10.40.0.20:5061
cert_file=${MM7_ASTERISK_CERT_FILE}
priv_key_file=${MM7_ASTERISK_KEY_FILE}
ca_list_file=${MM7_ASTERISK_CA_FILE}
verify_server=yes
method=tlsv1_2

EOF

for id in 7001 7002 7003 7004 7005 7006 7007; do
    var="MM7_SIP_PASSWORD_${id}"
    password=${!var-}
    if [[ -z "$password" ]]; then
        echo "missing required secret environment variable: $var" >&2
        exit 1
    fi
    if [[ "$password" == *$'\n'* || "$password" == *$'\r'* ]]; then
        echo "invalid newline in $var" >&2
        exit 1
    fi
    cat >>"$TMP" <<EOF
[${id}]
type=aor
max_contacts=1
remove_existing=yes

[${id}]
type=auth
auth_type=userpass
username=${id}
password=${password}

[${id}]
type=endpoint
aors=${id}
auth=${id}
transport=transport-tls
context=mm7-internal
direct_media=no
disallow=all
allow=alaw,ulaw
media_encryption=sdes
media_encryption_optimistic=no
rewrite_contact=no
rtp_symmetric=no
force_rport=no

EOF
done

chmod 600 "$TMP"
mv -f "$TMP" "$OUTPUT"
trap - EXIT
chmod 600 "$OUTPUT"

echo "rendered private Asterisk/PJSIP configuration: $OUTPUT"
